//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Bid { get; set; }
        public string Btitle { get; set; }
        public string Bcategory { get; set; }
        public string Bdesc { get; set; }
        public string Burl { get; set; }
    }
}
